import { BsFillCameraVideoFill } from "react-icons/bs";
import { BsFillPersonFill } from "react-icons/bs";
import { FaPlus } from "react-icons/fa";
import { BsArrowReturnLeft } from "react-icons/bs";
const camera = BsFillCameraVideoFill;
const person = BsFillPersonFill;
const plus = FaPlus;
const arrow = BsArrowReturnLeft;

export const studies = [
  {
    id: 1,
    link: "/case-studies/eci-7-resolutions-digital-marketing",
    logo: "eci",
    img: "eci-7-resolutions",
    name: "7 Resolutions",
    tag: "Digital Marketing",
  },
  {
    id: 2,
    link: "/case-studies/csi-12-days-of-christmas-digital-marketing",
    logo: "csi",
    img: "csi-12-days",
    name: "12 Days of Christmas",
    tag: "Digital Marketing",
  },
  {
    id: 3,
    link: "/case-studies/cdw-grounds-for-security-content-marketing",
    logo: "cdw",
    img: "cdw-grounds",
    name: "Grounds for Security",
    tag: "Content Marketing",
  },
  {
    id: 4,
    link: "/case-studies/cradlepoint-pinpoint-strategy-branding-proposition",
    logo: "cradlepoint",
    img: "cradlepoint-pinpoint",
    name: "Pinpoint",
    tag: "Strategy, Branding and Proposition",
  },
  {
    id: 5,
    link: "/case-studies/dell-technologies-video-content-marketing",
    logo: "dell-technologies",
    img: "cdw-dell",
    name: "Dell Technologies Video",
    tag: "Content Marketing",
  },
  {
    id: 6,
    link: "/case-studies/check-point-straight-to-the-point-content-marketing",
    logo: "check-point",
    img: "checkpoint-straight-to-the-point",
    name: "Straight to the Point",
    tag: "Content Marketing",
  },
  {
    id: 7,
    link: "/case-studies/check-point-partner-awards-2021-strategy-branding-proposition",
    logo: "check-point",
    img: "checkpoint-pa21",
    name: "Partner Awards 2021",
    tag: "Strategy, Branding and Proposition",
  },
  {
    id: 8,
    link: "/case-studies/e2e-assure-company-animation-strategy-branding-proposition",
    logo: "e2e-assure",
    img: "e2e-assure-animation",
    name: "Company Animation",
    tag: "Strategy, Branding and Proposition",
  },
  {
    id: 9,
    link: "/case-studies/eci-lead-generation-posters-abm",
    logo: "eci",
    img: "eci-forcepoint",
    name: "Lead Generation Posters",
    tag: "ABM",
  },
  {
    id: 10,
    link: "/case-studies/e92-plus-mdr-calculator-digital-marketing",
    logo: "e92-plus",
    img: "e92plus-calculator",
    name: "MDR Calculator",
    tag: "Digital Marketing",
  },
  {
    id: 11,
    link: "/case-studies/netally-wifi-wonder-person-abm",
    logo: "netally",
    img: "netally",
    name: "WiFi Wonder person",
    tag: "ABM",
  },
  {
    id: 12,
    link: "/case-studies/check-point-partner-awards-2022-strategy-branding-proposition",
    logo: "check-point",
    img: "checkpoint-pa22",
    name: "Partner Awards 2022",
    tag: "Strategy, Branding and Proposition",
  },
  {
    id: 13,
    link: "/case-studies/scc-phillips-product-quiz-gamification",
    logo: "scc",
    img: "scc-quiz",
    name: "Phillips Product Quiz",
    tag: "Gamification",
  },
  {
    id: 14,
    link: "/case-studies/softwareone-softwareone-duet-gamification",
    logo: "software-one",
    img: "software-one",
    name: "SoftwareONE Duet",
    tag: "Gamification",
  },
  {
    id: 15,
    link: "/case-studies/red-hat-innovation-island-gamification",
    logo: "red-hat",
    img: "innovation-island",
    name: "Innovation Island",
    tag: "Gamification",
  },
  {
    id: 16,
    link: "/case-studies/abacus-forged-coins-abm",
    logo: "abacus",
    img: "abacus",
    name: "Forged Coins",
    text: "Stone2Stone worked with Abacus to create messaging that highlighted how in-house penetration testing can provide businesses with a comprehensive understanding of their cybersecurity strengths and weaknesses.",
    challenge:
      "Abacus aimed to develop a campaign highlighting the potential of their recent acquisition, Gotham Security, in bolstering cybersecurity defenses proactively, prior to any cyber-attack.",
    target: "New, potential and existing Abacus and Gotham Security customers.",
    solution:
      "A co-branded coin displayed both the Abacus and Gotham Security logos. It was packaged in an engaging booklet, accompanied by emails and a landing page.",
    outcome:
      "This campaign successfully attracted 15 new customer opportunities, while also bringing back two returning customers, consolidating the customer base and driving business growth.",
    icon1: person(),
    icon2: plus(),
    icon3: arrow(),
    result1: "100 Targets Identified",
    result2: "15 New Customer Opportunities",
    result3: "2 Returning Customers",
    tag: "ABM",
  },
  {
    id: 17,
    link: "/case-studies/forescout-graphic-event-hoodie-strategy-branding-proposition",
    logo: "forescout",
    img: "forescout-hoodie",
    name: "Graphic Event Hoodie",
    tag: "Strategy, Branding and Proposition",
  },
  {
    id: 18,
    link: "/case-studies/trend-micro-aws-event-video-content-marketing",
    logo: "trend-micro",
    img: "trendmicro-aws",
    name: "AWS Event Video",
    tag: "Content Marketing",
  },
  {
    id: 19,
    link: "/case-studies/forescout-infosecurity-event-video-content-marketing",
    logo: "forescout",
    img: "forescout-infosecurity",
    name: "Infosecurity Event Video",
    tag: "Content Marketing",
  },
  {
    id: 20,
    link: "/case-studies/scc-company-animation-strategy-branding-proposition",
    logo: "scc",
    img: "scc-animation",
    name: "Company Animation",
    tag: "Strategy, Branding and Proposition",
  },
];
