export const studies = [
  {
    id: 1,
    link: "/",
    logo: "eci",
    img: "eci-7-resolutions",
    name: "7 Resolutions",
    type: "Digital Marketing",
  },
  {
    id: 2,
    link: "/",
    logo: "csi",
    img: "csi-12-days",
    name: "12 Days of Christmas",
    type: "Digital Marketing",
  },
  {
    id: 3,
    link: "/",
    logo: "cdw",
    img: "cdw-grounds",
    name: "Grounds for Security",
    type: "Content Marketing",
  },
  {
    id: 4,
    link: "/",
    logo: "cradlepoint",
    img: "cradlepoint-pinpoint",
    name: "Pinpoint",
    type: "Strategy, Branding and Proposition",
  },
  {
    id: 5,
    link: "/",
    logo: "dell-technologies",
    img: "cdw-dell",
    name: "Dell Technologies Video",
    type: "Content Marketing",
  },
  {
    id: 6,
    link: "/",
    logo: "check-point",
    img: "checkpoint-straight-to-the-point",
    name: "Straight to the Point",
    type: "Content Marketing",
  },
  {
    id: 7,
    link: "/",
    logo: "check-point",
    img: "checkpoint-pa21",
    name: "Partner Awards 2021",
    type: "Strategy, Branding and Proposition",
  },
  {
    id: 8,
    link: "/",
    logo: "e2e-assure",
    img: "e2e-assure-animation",
    name: "Company Animation",
    type: "Strategy, Branding and Proposition",
  },
  {
    id: 9,
    link: "/",
    logo: "eci",
    img: "eci-forcepoint",
    name: "Lead Generation Posters",
    type: "ABM",
  },
  {
    id: 10,
    link: "/",
    logo: "e92-plus",
    img: "e92plus-calculator",
    name: "MDR Calculator",
    type: "Digital Marketing",
  },
  {
    id: 11,
    link: "/",
    logo: "netally",
    img: "netally",
    name: "WiFi Wonder person",
    type: "ABM",
  },
  {
    id: 12,
    link: "/",
    logo: "check-point",
    img: "checkpoint-pa22",
    name: "Partner Awards 2022",
    type: "Strategy, Branding and Proposition",
  },
  {
    id: 13,
    link: "/",
    logo: "scc",
    img: "scc-quiz",
    name: "Phillips Product Quiz",
    type: "Gamification",
  },
  {
    id: 14,
    link: "/",
    logo: "software-one",
    img: "software-one",
    name: "SoftwareONE Duet",
    type: "Gamification",
  },
  {
    id: 15,
    link: "/",
    logo: "red-hat",
    img: "innovation-island",
    name: "Innovation Island",
    type: "Gamification",
  },
  {
    id: 16,
    link: "/",
    logo: "abacus",
    img: "abacus",
    name: "Forged Coins",
    type: "ABM",
  },
  {
    id: 17,
    link: "/",
    logo: "forescout",
    img: "forescout-hoodie",
    name: "Graphic Event Hoodie",
    type: "Strategy, Branding and Proposition",
  },
  {
    id: 18,
    link: "/",
    logo: "trend-micro",
    img: "trendmicro-aws",
    name: "AWS Event Video",
    type: "Content Marketing",
  },
  {
    id: 19,
    link: "/",
    logo: "forescout",
    img: "forescout-infosecurity",
    name: "Infosecurity Event Video",
    type: "Content Marketing",
  },
  {
    id: 20,
    link: "/",
    logo: "scc",
    img: "scc-animation",
    name: "Company Animation",
    type: "Strategy, Branding and Proposition",
  },
];
